Repository VirtoCommerce/vc-platform, pull requests merged in 2022-04, with the labels that each got.

#2486 Optimize caching in CrudService
  src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
  src/VirtoCommerce.Platform.Core/Extensions/DictionaryExtension.cs
  src/VirtoCommerce.Platform.Core/Extensions/EnumerableExtensions.cs
  src/VirtoCommerce.Platform.Core/Extensions/ObjectExtension.cs
  src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
Labels: review task created

#2489 Add response group to the cache key prefix
  src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
  src/VirtoCommerce.Platform.Core/Extensions/EnumerableExtensions.cs
  src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
Labels: review task created

#2485 Add extension methods
  src/VirtoCommerce.Platform.Core/GenericCrud/SearchServiceExtensions.cs
  src/VirtoCommerce.Platform.Core/Security/IPermissionsRegistrarExtensions.cs
  src/VirtoCommerce.Platform.Core/Settings/SettingsExtension.cs
Labels: review task created

#2490 Simplify signature and usage of GetOrLoadByIdsAsync()
  src/VirtoCommerce.Platform.Core/Caching/MemoryCacheExtensions.cs
  src/VirtoCommerce.Platform.Data/GenericCrud/CrudService.cs
Labels: review task created

#2493 PT-2295: Add collapsible tooltips in settings
  src/VirtoCommerce.Platform.Web/wwwroot/Localizations/de.VirtoCommerce.Platform.json
  src/VirtoCommerce.Platform.Web/wwwroot/Localizations/en.VirtoCommerce.Platform.json
  src/VirtoCommerce.Platform.Web/wwwroot/Localizations/ru.VirtoCommerce.Platform.json
  src/VirtoCommerce.Platform.Web/wwwroot/css/themes/main/sass/modules/_cosmetic.sass
  src/VirtoCommerce.Platform.Web/wwwroot/js/app/settings/blades/settings-detail.tpl.html
Labels: deploy-qa

#2494 PT7232: Checking of hide method is added for toolbar commands
  src/VirtoCommerce.Platform.Web/wwwroot/js/app/navigation/blade/bladeContainer.tpl.html
Labels: review task created, deploy-qa
